### ISSUE TITLE
Task 1.1.1.6 PATCH has a typo and Task 1.1.1.7 | PATCH fails because the module is built in the kernel.

### ISSUE THREAD

**Issue by akadoya** [ansible-lockdown/DEBIAN12-CIS#83]
**Have you checked [ReadtheDocs](https://ansible-lockdown.readthedocs.io/en/latest/)?:**

yes

**Describe the Issue**

- [L189](https://github.com/ansible-lockdown/DEBIAN12-CIS/blob/devel/tasks/section_1/cis_1.1.1.x.yml#L189) is about overlayfs but the task is executed against squashfs. (typo?)

- The task below fails on Debian 12 build because squashfs is built in the kernel. In Ubuntu24 CIS lockdown role, there was a [prelim task](https://github.com/ansible-lockdown/UBUNTU24-CIS/blob/devel/tasks/prelim.yml#L17-L24) to check this as a condition -  Can Debian implement a similar logic as well?

```
    - name: "1.1.1.7 | PATCH | Ensure squashfs kernel module is not available | Disable squashfs"
      when: not system_is_container
      community.general.modprobe:
        name: squashfs
        state: absent
```

**Expected Behavior**

- overlayfs task execute action against overlayfs
- squashfs cannot be disabled with modprobe module when it's built in the kernel so add it as a prelim condition check, skip if that is the case.

**Actual Behavior**

- overlayfs task would execute action against squashfs
- patch tasks fails with fatal error

**Control(s) Affected**

- 1.1.1.6
- 1.1.1.7

**Environment (please complete the following information):**

- branch being used: 1.0.1
- Ansible Version: 2.18.6
- Host Python Version: 3.11.2
- Ansible Server Python Version: 3.13.3
- Additional Details: Tested on Debian12 / kernel 6.8.12-11

**Additional Notes**
Anything additional goes here

**Possible Solution**

Mentioned above.
